### ISSUE TITLE
Add a function to make the script romanisim_make_image callable from python

### ISSUE THREAD

**Issue by sanjibs** [spacetelescope/romanisim#118]
For many applications it is necessary to run the romanisim programmitically from python.  For this we need a  function that takes in user defined parameters as a dictionary or keyword arguments and sets the unspecified parameters to default values and then runs and generates the images.

**Comment by schlafly** [comment]
I kind of claim that this is already done; romanisim-make-image is really only handling the parsing of the CLI.  Python code can go ahead and directly call image.simulate.
https://github.com/spacetelescope/romanisim/blob/main/romanisim/image.py#L673

**Comment by sanjibs** [comment]
The suggestion is to simply make the  go(args) function in romanisim-make-image.py file callable from python. image.simulate can be used but requires a lot of extra lines of code to take some user input aguments and produce an output image file.
