### ISSUE TITLE
resolve SonarScan issues

### ISSUE THREAD

**Issue by zacharyburnett** [spacetelescope/romanisim#122]
Before the regression tests can be run in [`spacetelescope/RegressionTests`](https://github.com/spacetelescope/RegressionTests/actions/workflows/romanisim.yml), these issues must be resolved (ITSD requires that all code running on on-prem hardware pass SonarScan), or marked as non-issues. 

https://plsonarqube.stsci.edu/project/issues?resolved=false&types=BUG&inNewCodePeriod=true&id=romanisim

all of these issues appear in the cython-generated `romanisim/ramp_fit_casertano.c` file, so I imagine that debugging them might be difficult; @schlafly can I mark any of these as "wontfix" or "false-positive"?

- [ ] `Out of bound memory access (access exceeds upper limit of memory block)`
  ```c
        (__pyx_v_p[__pyx_v_i]) = Py_None;
  ```
- [ ] `Division by zero`
  ```c
      __pyx_v_new_shape = ((__pyx_v_stop - __pyx_v_start) / __pyx_v_step);
  ```
- [ ] `Access to field '__pyx_vtab' results in a dereference of a null pointer (loaded from field 'memview')`
  ```c
    __pyx_t_2 = ((struct __pyx_vtabstruct_memoryview *)((struct __pyx_memoryview_obj *)__pyx_v_memviewslice.memview)->__pyx_vtab)->_get_base(((struct __pyx_memoryview_obj *)__pyx_v_memviewslice.memview)); if (unlikely(!__pyx_t_2)) __PYX_ERR(1, 1018, __pyx_L1_error)
  ```
- [ ] `Out of bound memory access (access exceeds upper limit of memory block)`
  ```c
      __pyx_t_2 = ((__pyx_v_mslice->shape[__pyx_v_i]) > 1);
  ```
- [ ] `Out of bound memory access (access exceeds upper limit of memory block)`
  ```c
        (__pyx_v_strides[__pyx_v_idx]) = __pyx_v_stride;
  ```
- [ ] `Out of bound memory access (access exceeds upper limit of memory block)`
  ```c
      (__pyx_v_mslice->shape[(__pyx_v_i + __pyx_v_offset)]) = (__pyx_v_mslice->shape[__pyx_v_i]);
  ```
- [ ] `Undefined or garbage value returned to caller`
  ```c
    return __pyx_r;
  ```
- [ ] `Undefined or garbage value returned to caller`
  ```c
    return __pyx_r;
  ```
- [ ] `Array subscript is undefined`
  ```c
    __pyx_r = ((__pyx_v_9romanisim_18ramp_fit_casertano_PTABLE[1])[__pyx_v_i]);
  ```
- [ ] `Address of stack memory associated with local variable 'ctx' is still referred to by the stack variable 'stack' upon returning to the caller. This will be a dangling reference`
  ```c
      return retval;
  ```

**Comment by schlafly** [comment]
Yeah.  As you say, these are all in the cython-generated code so it's possible that fixes would need to come in as fixes to cython, if these are real?  We do explicitly turn off some range checking here
https://github.com/spacetelescope/romanisim/blob/main/romanisim/ramp_fit_casertano.pyx#L22-L25
because we try to do a lot of bounds checking before then to get it out of the inner loop.  I do not know enough about sonarqube to have a sense for how seriously I should take these.
