### ISSUE TITLE
Roman I-Sim: truncated MA Tables

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romanisim#150]
_Issue [RCAL-902](https://jira.stsci.edu/browse/RCAL-902) was created on JIRA by [Andrea Bellini](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bellini):_

Bookkeeping ticket to track work already done on issues related to truncated MA Tables in Roman I-Sim (crf. PR#&#x2060;131).

**Comment by schlafly** [comment]
This was addressed in #131 , closing.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly) on [JIRA](https://jira.stsci.edu/browse/RCAL-902?focusedCommentId=718068#comment-718068):_

This was addressed in <https://github.com/spacetelescope/romanisim/pull/131],> closing.
