### ISSUE TITLE
Default MATAB argument

### ISSUE THREAD

**Issue by Skyhawk172** [spacetelescope/romanisim#189]
Using the `romanisim-make-image` script, the default `ma_table_number` is set to 1, but this value is not valid anymore since the implementation of the new hard-coded MA tables. 

In `ris_make_utils.set_metadata` (and in other places as well), the default `ma_table_number` is set to 4. It looks like a quick fix is to update the default value of the parser in the `romanisim-make-image` script.

However, when I specify an `ma_table_number` of 4 (the default), then I get the following error:

> CRDS - ERROR -  Error determining best reference for 'dark'  =    parameter='ROMAN.META.EXPOSURE.MA_TABLE_NUMBER' value='17.0' is not in ['1.0', '101.0', '102.0', '103.0', '104.0', '105.0', '106.0', '107.0', '108.0', '109.0', '110.0']

@eunkyuh

**Comment by Skyhawk172** [comment]
The 17 is just because we tried a few different values... but we knew they wouldn't work based on the code.

Also, thanks for pointing our the CRDS server... That reminded me that I'm using a  specific _outdated_ context. I'm now using the latest context (0065) and it's running now, _as long as I override the default MATAB number._

So the only thing remaining minor thing to fix is the default `ma_table_number` when parsing the command line arguments.

**Comment by schlafly** [comment]
Great, yes, that's what #191 does.  I'll go ahead and merge.
