### ISSUE TITLE
Installing issue (Apple M1 MacOS 13)

### ISSUE THREAD

**Issue by wlim-ipac** [spacetelescope/romanisim#86]
Do you have a workaround to resolve following issue with fftw3 library?

  Downloading GalSim-2.5.0.tar.gz (8.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 63.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Using setuptools version 68.2.2
      Python version =  3.10.7 (v3.10.7:6cc6b13308, Sep  5 2022, 14:02:52) [Clang 13.0.0 (clang-1300.0.29.30)]
      Looking for Eigen:
         /Library/Frameworks/Python.framework/Versions/3.10/include  (no)
         /usr/local/include  (no)
         downloaded_eigen/eigen-3.4.0  (yes)
      GalSim version is 2.5.0
      running dist_info
      creating /private/var/folders/y7/l7hsphn16lg7tr1p1jwj7ch40005gq/T/pip-modern-metadata-lgmc8mjf/GalSim.egg-info
      writing /private/var/folders/y7/l7hsphn16lg7tr1p1jwj7ch40005gq/T/pip-modern-metadata-lgmc8mjf/GalSim.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/y7/l7hsphn16lg7tr1p1jwj7ch40005gq/T/pip-modern-metadata-lgmc8mjf/GalSim.egg-info/dependency_links.txt
      writing entry points to /private/var/folders/y7/l7hsphn16lg7tr1p1jwj7ch40005gq/T/pip-modern-metadata-lgmc8mjf/GalSim.egg-info/entry_points.txt
      writing requirements to /private/var/folders/y7/l7hsphn16lg7tr1p1jwj7ch40005gq/T/pip-modern-metadata-lgmc8mjf/GalSim.egg-info/requires.txt
      writing top-level names to /private/var/folders/y7/l7hsphn16lg7tr1p1jwj7ch40005gq/T/pip-modern-metadata-lgmc8mjf/GalSim.egg-info/top_level.txt
      writing manifest file '/private/var/folders/y7/l7hsphn16lg7tr1p1jwj7ch40005gq/T/pip-modern-metadata-lgmc8mjf/GalSim.egg-info/SOURCES.txt'
      Looking for  libfftw3.dylib
      Could not find fftw3 library.  Make sure it is installed either in a standard
      location such as /usr/local/lib, or the installation directory is either in
      your LIBRARY_PATH or FFTW_DIR environment variable.
      error:
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by schlafly** [comment]
This is an issue with galsim on Apple Arm systems.  There's some information about this on Galsim's installation pages.  A couple of people have been successful following the description there.  We briefly mention this on the installation page here
https://romanisim.readthedocs.io/en/latest/romanisim/install.html
but I'd welcome more information.  I don't personally have one of these systems and have no first hand experience.

**Comment by wlim-ipac** [comment]
Thanks. 
I could not find the corresponding information from GalSim installation instruction as well.
I may raise a ticket for GalSim.

**Comment by schlafly** [comment]
See here:
https://galsim-developers.github.io/GalSim/_build/html/install_pip.html#installing-fftw
Two or three people here have been able to install FFTW separately and pass the appropriate environment variable.  I can put you in touch with them if you get stuck.

**Comment by wlim-ipac** [comment]
Thanks Eddie!
It seems to be installing properly.
Sorry for this late reply.
Last and this weeks are quite overwhelming so could not get back to this issue.
You can close this ticket since my installation issue by FFTW is resolved based on the information in the link you provided above.

**Comment by schlafly** [comment]
Thanks, closing!
