### ISSUE TITLE
read_pattern is not being set to match used ma table

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/romanisim#88]
The meta value `meta.exposure.read_pattern` is not being set to match the ma table in use. Example using the MA table "2", which, according to `parameters.py` is a 5-resultant table. However, `read_pattern` has six resultants. Use of any ma table results in the same `read_pattern`:

```
$ romanisim-make-image --level 1 --ma_table_number 2 random_uncal.asdf
$ python
>>> import roman_datamodels as rdm
>>> m = rdm.open('random_uncal.asdf')
>>> m.meta.exposure.read_pattern
LNode([[1], [2, 3], [4], [5, 6, 7, 8], [9, 10], [11]])
>>> m.data.shape
(5, 4096, 4096)
```

**Comment by schlafly** [comment]
Oh yeah, we wrote this before read_pattern existed; read_pattern presumably always takes that garbage value.
